#!/usr/bin/env python3
"""Build _data/authors.yml from the _people/ files.

Each person's canonical name is its `name`; variants are `name`, the name with
any parenthetical nickname removed, and any `name_variants` listed in the person
file (a.k.a. names, spelling variants, and initial forms found in the bib). The
PI keeps a hand-tuned variant set. Run this, then `bib_to_json.py`.

Also seeds a set of known aliases into the person files (idempotent) so the data
lives with the person, not just in the generated map.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PEOPLE = ROOT / "_people"
AUTHORS = ROOT / "_data" / "authors.yml"

# Aliases discovered by the surname audit (same person, different published form).
SEED_ALIASES = {
    "vahid-mirnezami": ["Seyed Vahid Mirnezami"],
    "sai-kiranmayee-samudrala": ["S.K. Samudrala"],
    "kibona-ku": ["Kibon Ku"],
    "bitgoeul-kim": ["B. F. Kim"],
    "daniel-stoecklein": ["D Wilfried Stoecklein"],
    "sangeet-balakrishnan": ["Sangeeth Balakrishnan"],
    "kahnietta-pr-out": ["Kahntinetta Monique Pr'Out"],
    "david-ackerman": ["D L Ackerman"],
}

BASKAR = [
    '- canonical: "B. Ganapathysubramanian"',
    "  person: baskar",
    "  variants:",
    '    - "Baskar Ganapathysubramanian"',
    '    - "B Ganapathysubramanian"',
    '    - "Ganapathysubramanian, B."',
    '    - "B. Ganapathysubramanian"',
]


def fm(text, key):
    m = re.search(rf'^{key}:\s*"?([^"\n]+?)"?\s*$', text, re.M)
    return m.group(1).strip() if m else ""


def fm_list(text, key):
    m = re.search(rf'^{key}:\s*\[([^\]]*)\]', text, re.M)
    return re.findall(r'"([^"]*)"', m.group(1)) if m else []


def seed_aliases():
    """Ensure each person file carries its known aliases in name_variants."""
    for slug, aliases in SEED_ALIASES.items():
        f = PEOPLE / f"{slug}.md"
        if not f.exists():
            print(f"  WARN missing {slug}"); continue
        t = f.read_text()
        existing = fm_list(t, "name_variants")
        merged = existing[:]
        for a in aliases:
            if a not in merged:
                merged.append(a)
        vlist = "[" + ", ".join(f'"{v}"' for v in merged) + "]"
        if "name_variants:" in t:
            t = re.sub(r"^name_variants:.*$", f"name_variants: {vlist}", t, count=1, flags=re.M)
        else:
            t = re.sub(r"(^name:.*$)", r"\1\n" + f"name_variants: {vlist}", t, count=1, flags=re.M)
        f.write_text(t)


def build():
    rows = ["# Canonical author name map (PLAN.md Section 4/6.3). Generated by",
            "# scripts/build_authors.py from _people/. Edit person files, not this.",
            *BASKAR]
    for f in sorted(PEOPLE.glob("*.md")):
        t = f.read_text()
        name, slug = fm(t, "name"), fm(t, "slug")
        if slug == "baskar" or not name or not slug:
            continue
        no_paren = re.sub(r"\s*\([^)]*\)\s*", " ", name).strip()
        variants = []
        for v in [name, no_paren, *fm_list(t, "name_variants")]:
            if v and v not in variants:
                variants.append(v)
        rows.append(f'- canonical: "{name}"')
        rows.append(f"  person: {slug}")
        rows.append("  variants:")
        for v in variants:
            rows.append(f'    - "{v}"')
    AUTHORS.write_text("\n".join(rows) + "\n")
    print(f"authors.yml built from {len(list(PEOPLE.glob('*.md')))} person files")


if __name__ == "__main__":
    seed_aliases()
    build()
